clear

% chamadas válidas: devem continuar funcionando
test_result_builtin_signature_arity_validation(1,1) = isequal(class(1), class(1))
test_result_builtin_signature_arity_validation(2,1) = isequal(isa(1, "double"), isa(1, "double"))

test_result_builtin_signature_arity_validation(3,1) = isequal(dbstack(), dbstack())
test_result_builtin_signature_arity_validation(4,1) = isequal(dbstack(0), dbstack(0))
test_result_builtin_signature_arity_validation(5,1) = isequal(dbstack("-completenames"), dbstack("-completenames"))
test_result_builtin_signature_arity_validation(6,1) = isequal(dbstack(0, "-completenames"), dbstack(0, "-completenames"))

test_result_builtin_signature_arity_validation(7,1) = isequal(exist("sin"), exist("sin"))
test_result_builtin_signature_arity_validation(8,1) = isequal(exist("sin", "builtin"), exist("sin", "builtin"))

test_result_builtin_signature_arity_validation(9,1) = isequal(which("sin"), which("sin"))

test_result_builtin_signature_arity_validation(10,1) = isequal(func2str(@sin), func2str(@sin))
test_result_builtin_signature_arity_validation(11,1) = isequal(str2func("sin"), str2func("sin"))

test_result_builtin_signature_arity_validation(12,1) = isequal(feval("@(x) x + 1", 4), feval("@(x) x + 1", 4))

test_result_builtin_signature_arity_validation(13,1) = isequal(functions(@sin), functions(@sin))

test_result_builtin_signature_arity_validation(14,1) = isequal(localfunctions(), localfunctions())

test_result_builtin_signature_arity_validation(15,1) = isequal(nargin("feval"), nargin("feval"))
test_result_builtin_signature_arity_validation(16,1) = isequal(nargout("feval"), nargout("feval"))

nargin() % erro esperado fora de função/lambda
nargout() % erro esperado fora de função/lambda

test_result_builtin_signature_arity_validation(17,1) = isequal(narginchk(0, 2), narginchk(0, 2))
test_result_builtin_signature_arity_validation(18,1) = isequal(nargoutchk(0, 2), nargoutchk(0, 2))

test_result_builtin_signature_arity_validation(19,1) = isequal(eval("1 + 2"), eval("1 + 2"))
test_result_builtin_signature_arity_validation(20,1) = isequal(eval("missingEvalValue", "33"), eval("missingEvalValue", "33"))

test_result_builtin_signature_arity_validation(21,1) = isequal(evalin("base", "1 + 2"), evalin("base", "1 + 2"))
test_result_builtin_signature_arity_validation(22,1) = isequal(evalin("base", "missingEvalinValue", "44"), evalin("base", "missingEvalinValue", "44"))

test_result_builtin_signature_arity_validation(23,1) = isequal(assignin("base", "createdByAssignin", 123), assignin("base", "createdByAssignin", 123))
test_result_builtin_signature_arity_validation(24,1) = isequal(createdByAssignin, createdByAssignin)

inputname(1) % erro esperado: fora de função/lambda, mas aridade correta

% aridade inválida: todos devem lançar Invalid call to ...
class() % error: Invalid call to ...
class(1, 2) % error: Invalid call to ...

isa(1) % error: Invalid call to ...
isa(1, "double", 3) % error: Invalid call to ...

dbstack(1, "-completenames", 2) % error: Invalid call to ...

exist() % error: Invalid call to ...
exist("sin", "builtin", 3) % error: Invalid call to ...

which() % error: Invalid call to ...
which("sin", "extra") % error: Invalid call to ...

func2str() % error: Invalid call to ...
func2str(@sin, @cos) % error: Invalid call to ...

str2func() % error: Invalid call to ...
str2func("sin", "cos") % error: Invalid call to ...

feval() % error: Invalid call to ...

functions() % error: Invalid call to ...
functions(@sin, @cos) % error: Invalid call to ...

localfunctions(1) % error: Invalid call to ...

nargin(1, 2) % error: Invalid call to ...
nargout(1, 2) % error: Invalid call to ...

narginchk(0) % error: Invalid call to ...
narginchk(0, 1, 2) % error: Invalid call to ...

nargoutchk(0) % error: Invalid call to ...
nargoutchk(0, 1, 2) % error: Invalid call to ...

inputname() % error: Invalid call to ...
inputname(1, 2) % error: Invalid call to ...

eval() % error: Invalid call to ...
eval("1", "2", "3") % error: Invalid call to ...

evalin("base") % error: Invalid call to ...
evalin("base", "1", "2", "3") % error: Invalid call to ...

assignin("base", "x") % error: Invalid call to ...
assignin("base", "x", 1, 2) % error: Invalid call to ...


complete_test_result_builtin_signature_arity_validation = all(test_result_builtin_signature_arity_validation)

complete_test_result_builtin_signature_arity_validation
